version: 1.1
kind: component
name: spacy-streamlit-app
tags: [spacy, streamlit]
run:
  kind: service
  ports: [8501]
  rewritePath: true
  container:
    image: polyaxon/polyaxon-examples:spacy-streamlit-demo
    command: [streamlit, run, app.py]
